### ISSUE TITLE
Actions Container: Measures Panel

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-package-viewer#1]
# Description

The [Measures Panel of the Actions container](https://github.com/openspending/fiscal-data-package-viewer/blob/master/src/scripts/components/panels/Actions.js#L13) Displays a list of measures in the data.

Measures in Fiscal Data Package as always monetary amounts.

These measures are exposed to the user as a set of buttons that enable the user to make a selection (one at a time), which each selection updates the *state* of the view: specifically, the measure being viewed.

If there is only one measure in a dataset (which is extremely common), then, that measure should always be selected, and cannot be changed by a user.

# Tasks

* [x] Let the user select a measure from available measures
* [x] There is always one measure selected
* [x] If there is only one measure, it is selected and cannot be unselected
* [x] Write tests for the `MeasureCodeList ` component (or whatever component holds all this functionality). [shallow rendering](http://facebook.github.io/react/docs/test-utils.html#shallow-rendering) looks to be the best way to test the output of a component

**Comment by pwalsh** [comment]
DONE.
