### ISSUE TITLE
Standalone Bubble Tree component

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-package-viewer#10]
# Description

The OpenSpending Bubble Tree is one of the most enduring views on fiscal data. We need to port this to the current codebase (and possibly clean up the code a bit in the process).

* https://github.com/openspending/openspendingjs/tree/master/lib/vendor/bubbletree/2.0 
* https://github.com/okfn/bubbletree

# Tasks

* [x] Extract out the Bubble Tree from wherever it lives into a standalone library
* [x] Write a React component that wraps the Bubble Tree
* [x] Expose the Bubble Tree as a view in the application

**Comment by pwalsh** [comment]
DONE
