### ISSUE TITLE
Package load component

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-package-viewer#12]
# Description

We've currently added a convenience input field to paste in any URL to a data package in order to initialise the app. This is a great step. Let's take it a little further in a way that will suit a number of immediate use cases we have. These use cases are:

1. Simply use the app to view a single Fiscal Data Package
2. Use the app to view a number of known Fiscal Data Packages

In the first case, the app simply initialises with the data from the known data package.

In the second case, the app initialises with the first data package in an array of known data packages. The app also exposes a UI element that allows the user to switch between packages. On switching the app destroys itself and reinitialises with the data from the new package.

# Tasks

* [x] The app can read a variable that is globally available (use case: the app code is included in an html page, and also there is a var in the html page)
  * [x] `var dataPackages = []`
    * An array of URLs to Fiscal Data Packages
* [x] A component that handles the switching of data packages in the viewer. 
  * If `dataPackages` is a length of 1, then this component does not display at all
  * If the `dataPackages` array is greater than 1, then, this component exposes a drop down selector of the packages. The first package in the array is active
  * If the `dataPackages` array is 0, then the app can't initialise at all - show an empty screen with a simple message.
* [x] Basic tests
* [x] Add the following to our index.html for use:

```
var dataPackages = [
  'https://raw.githubusercontent.com/os-data/boost-paraguay/master/datapackage.json',
  'https://raw.githubusercontent.com/os-data/boost-rio-grande-do-sul-revenue/master/datapackage.json',
  'https://raw.githubusercontent.com/openspending/fiscal-data-package-demos/master/boost-moldova/datapackage.json',
  'https://raw.githubusercontent.com/openspending/fiscal-data-package-demos/master/boost-moldova/datapackage.json'
]
```

For our current workflow, you can just include this in the `index.html` that is in the repository. When we are ready to package this viewer up, we'll be distributing the bundle and giving instructions for others to build their own `index.html`.

**Comment by pwalsh** [comment]
DONE.
