### ISSUE TITLE
UI enhancements

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-package-viewer#13]
# Description

# Tasks

* [x] In addition to the specific points below, just check that things are aligned nicely, and that it is a generally clean and usable layout.
* [x] Add a section at the top of the app that shows
  * [x] The title of the datapackage
  * [x] The description of the data package if it exists
  * [x] The selector for changing data packages should be in this section, right aligned
* [x] The selector for the data package should *always* show the current datapackage - it should never show None. Currently, on initial load it shows None. I'd expect it to show the first package URL, and, as soon as the FDP is parsed, show the title and description while waiting for the data to load
* [x] While waiting for data to load, just show a simple word "Loading..." in the centre of the app
* [x] Treemap and Pie need to show **money amounts of the selected measure**, not percentages :)
* [x] Put the table into a tab, along with the Treemap and the Pie chart, under a new tab called "Table"
* [x] Now with the Table view in the tabbed vis section
  * [x] Make the tab section use the full width of the content area
  * [x] Center the Treemap and Pie visualisations, and make them bigger
  * [x] Let the table take full width of the content area too
  * [x] Tidy up the table look (using default bootstrap options). Do reduce font size from normal bootstrap though. we can go at least 2px smaller, and also reduce padding/cell height
* [x] Fix the display of the measures panel
  * [x] Ensure that the buttons are *always* aligned horizontally
  * [x] Cut the length of the titles at a particular length and show full title on hover if needed to show horizontally - we should be able to show 4 measures horizontally so optimise for that
* [x] Fix the display of the dimensions panel
  * [x] In general, for both filters and groups, if a dimension only has a single value in its value list, then *do not display that dimension, as, it is not useful for the UI in any way
  * [x] We *always* need to group first, and only allow filters on the groups. This is because the UI is always supposed to be displaying aggregate data.
    * [x] Always have a least one or more dimensions selected as grouped
  * [x] Filters should always only show options that are relevant based on the selected groups
  * [x] Groups should be at the to, and filters underneath
* [x] Forward/Back buttons: always disable if the user gets to either end - disable to appropriate button if there is nowhere else to go
* [x] Add a section under the visualisations for extra stuff
  * [x] Title: "More information"
  * [x] Subtitle: "Resources"
    * [x] Text under resources: "This data package contains a resource called {x}".
    * [x] <del>See the raw data is a link to view the CSV in data pipes</del>

**Comment by pwalsh** [comment]
@cecilaki can you start to dump some ideas in here, even only from those screenshots for now.

**Comment by pwalsh** [comment]
DONE.
