### ISSUE TITLE
Actions Container: Dimensions Panel

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-package-viewer#2]
# Description

The [Dimensions Panel of the Actions container](https://github.com/openspending/fiscal-data-package-viewer/blob/master/src/scripts/components/panels/Actions.js#L20) Displays the *code lists* generated for each dimension in the data.

These code lists are exposed to the user as a set of buttons that enable the user to make a selection, which each selection updates the *state* of the view.

Users can make the following actions with dimension code lists:

* *Filter* the the results on one or many dimensions, thereby removing lines of data exposed to the view layer. 
* *Group* the results by one or many dimensions, thereby *summing* all the measures based on the grouping.

# Tasks

* [x] Let the user select the *filters* for the current view
* [x] Let the user select the *groups* for the current view
* [x] Display the current selections to the user. The user can add/remove selections at will
* [x] Write tests for the `DimensionCodeList ` component (or whatever component holds all this functionality). [shallow rendering](http://facebook.github.io/react/docs/test-utils.html#shallow-rendering) looks to be the best way to test the output of a component

**Comment by pwalsh** [comment]
DONE.
