### ISSUE TITLE
Views Panel: Table Visualisation

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-package-viewer#5]
# Description

The Table visualisation simple presents the current state of the data in a table view.

# Tasks

* [x] Display current state of data in the table view
* [x] If the table view width is wider than the available space for the table, then implement horizontal scrolling on the table
* [x] Write tests for the component that renders the table view

**Comment by pwalsh** [comment]
DONE.
