### ISSUE TITLE
Data Flow: Init Views from Data Source

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-package-viewer#6]
# Description

Currently, we populate the app with the [`mockStateTree`](https://github.com/openspending/fiscal-data-package-viewer/blob/master/src/scripts/index.js#L9) object for initial development purposes.

However, the app will be powered from a Fiscal Data Package, and the data access provided by [`fiscal-data-js`](https://github.com/openspending/fiscal-data-js), which takes care of reading the data package and outputting the data in the form that the app expects to work with.

# Tasks

* [x] Integrate `fiscal-data-js`
  * [x] Provide it with a Fiscal Data Package URL
  * [x] use the resulting state tree to initialise the app with data
* [x] Write tests for the integration

**Comment by pwalsh** [comment]
DONE.
